[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://rlvlvcwehcbqvxjwoqhq.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsdmx2Y3dlaGNicXZ4andvcWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Njc4NTMsImV4cCI6MjA3MzQ0Mzg1M30.8lwuGi_XD4digdJqBOoMIqEUfHNE9SYg1OIWWVALvHI"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200