#:schema node_modules/wrangler/config-schema.json
name = "ischoolgo-management"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[env.production.vars]
ENVIRONMENT = "production"